### ISSUE TITLE
insert and emptytable allowed

### ISSUE THREAD

**Issue by aptdavid** [michaelachrisco/ReadOnlyTraitLaravel#15]
Insert() function and truncate() is allowed when I try to implement this trait. I would consider those to also to be blocked for a read-only table.

Adding these functions to the trait seems to work for me.
`public function insert(){
      $class = get_called_class();
      throw new ReadOnlyException("Not allowed to persist changes in read-only model {$class}");
}`

`public function truncate(){
      $class = get_called_class();
      throw new ReadOnlyException("Not allowed to persist changes in read-only model {$class}");
}`

**Comment by michaelachrisco** [comment]
Nice catch! Would you like to send a PR with the methods?

**Comment by aptdavid** [comment]
First pull request.. I think I did it right.

**Comment by michaelachrisco** [comment]
Excellent! Thank you.

**Comment by aptdavid** [comment]
No problem. Thank you, this trait is very helpful.
