### ISSUE TITLE
Difference with Mysql readonly user

### ISSUE THREAD

**Issue by matiazar** [michaelachrisco/ReadOnlyTraitLaravel#37]
Hi, sorry for this question.. but whats the diference by making a user readonly on database?

thanks in advance

**Comment by matiazar** [comment]
I need to implement somethuing like this to an external database, so no user or model can write to it.. 
so that was my question... there is any problem to make a user readonly on mysql?

**Comment by michaelachrisco** [comment]
This library only works on Laravel Models. It throws an error before operations that would occur on the database. It doesn't make any database level changes. 

If you are trying to do this specifically to mysql, this might help: https://stackoverflow.com/questions/12349640/read-only-table-in-mysql
