### ISSUE TITLE
Laravel 9 compatibility issue

### ISSUE THREAD

**Issue by CyberLPKF** [michaelachrisco/ReadOnlyTraitLaravel#41]
When a recently upgrade my system that uses ReadOnlyTrait, the following error is showed:

Declaration of MichaelAChrisco\ReadOnly\ReadOnlyTrait::touch() must be compatible with Illuminate\Database\Eloquent\Model::touch($attribute = null)

To correct this error, I just change line 163 in ReadOnlyTrait:

public function touch()

to

public function touch($attribute = null)

And now it's working well.

Thanks.

BTW: Before I open this issue, I had try open a PR, but github doesn't allow me.

**Comment by michaelachrisco** [comment]
I can throw this on a quick PR and see if that works for you. Its been a while since Ive used the newest version of laravel so someone else may need to check.

**Comment by michaelachrisco** [comment]
@CyberLPKF what did you change? I see `public function touch($attribute = null)` here: 

https://github.com/michaelachrisco/ReadOnlyTraitLaravel/blob/96953c0b9c1a96040d56796021fc05c32cbcd924/src/ReadOnlyTrait.php#L159-L167

Which version are you using? If you are using v0.40, you should have the fix.

**Comment by michaelachrisco** [comment]
Yep that would do it. You just need to update to version 0.40 and you should be good. Or change it to your own fork. Either way should work. 

Hope that helps!

**Comment by CyberLPKF** [comment]
Package upgraded and works like a charm! 

Thank you.

**Comment by michaelachrisco** [comment]
NP! Hope you have great day.
