### ISSUE TITLE
PHP 8.1 compatability

### ISSUE THREAD

**Issue by Healyhatman** [michaelachrisco/ReadOnlyTraitLaravel#46]
Readonly is now a reserved word so you're going to have to change the folder.

**Comment by michaelachrisco** [comment]
Hmm thats an issue. 

I suppose I could tall it `mciahelachrisco/readonlytrait` instead of `readonly` within packagist.

**Comment by michaelachrisco** [comment]
For my own docs later: https://github.com/composer/packagist/issues/47 Looks like this is the procedure to change a name within Packagist.

**Comment by michaelachrisco** [comment]
Im having trouble recreating this issue. If anyone else has this issue let me know. Otherwise im going to let this sit. I really dont want to re-create the packagist instance, it could potentially give an "abandoned" message to every project using this trait and its really not abandoned :).

**Comment by michaelachrisco** [comment]
Closing this issue unless someone else has any issues.
