### ISSUE TITLE
Blocking UX

### ISSUE THREAD

**Issue by btxtiger** [michaelachrisco/ReadOnlyTraitLaravel#47]
One suggestion:
We could use the `@deprecated` annotation on the methods to have a disallowing highlighting in the editor:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/15804690/215713233-dfc54ea7-8159-4b07-87b2-548bc6707be0.png">

**Comment by michaelachrisco** [comment]
Nice good call, if you make a PR ill review!
