### ISSUE TITLE
Error VS return false

### ISSUE THREAD

**Issue by michaelachrisco** [michaelachrisco/ReadOnlyTraitLaravel#7]
I would like to have a discussion on the behavior of the ReadOnlyTrait. Should the methods Raise an error or should they simply return false?

Raising an error would tell the developer that the eloquent model method cannot be used. Returning false would let `$model->save()` still be used, but will not really save when the trait is active.

**Comment by luemic** [comment]
Hi,

I would prefer not to save the model by returning false. Raising an error prevents it from using it in production which is not a way to go when you have to import your data from a legacy system.

Kind regards

Michael

**Comment by michaelachrisco** [comment]
Thanks @luemic for the feedback. This behavior is something I was encountering inconsistently in some MVC type of systems. Ill keep the current implementation.

**Comment by michaelachrisco** [comment]
Reopening this issue as per Laravel internals conversation here:
https://github.com/laravel/internals/issues/396

Example of ReadOnlyException: https://gist.github.com/jbruni/3f6de84d8b6ca96cf574bb2b41671916

**Comment by cyberhicham** [comment]
ReadOnlyException for me, you can catch them easily without alterating your code for checking whenever the model try to change the database and got 'false' return

My specific need for now if withing the impersonating feature that I need to implement, an Admin will impersonate a user to check his account but in readonly mode.

**Comment by michaelachrisco** [comment]
Non-DRY version here: 7-readonly-ex

**Comment by michaelachrisco** [comment]
@cyberhicham Updated the branch for explicit ReadOnlyException instead of an Exception. Thinking of a PR and version bump.

**Comment by cyberhicham** [comment]
@michaelachrisco : thanks ! I'll get back to it when implementing impersonating feature in a future project :)
