### ISSUE TITLE
set as readonly

### ISSUE THREAD

**Issue by michaelachrisco** [michaelachrisco/ReadOnlyTraitLaravel#8]
Rails has an easy method to use on their models:
http://apidock.com/rails/v4.2.7/ActiveRecord/Core/readonly%21

Implementing an easy to use method on the models would be superior to monkey-patching the eloquent models. 

Thoughts?

**Comment by VeeeneX** [comment]
Sure! Great feature

**Comment by michaelachrisco** [comment]
Closing as I am not sure how this would work ATM with the current laravel models.
